### ISSUE TITLE
Yarn version

### ISSUE THREAD

**Issue by SolDev69** [ThisTestUser/FarLandsChronicles#2]
No yarn equivalent of NoiseGeneratorOctaves. Please do a tutorial on how to bring back the farlands in yarn.

**Comment by ThisTestUser** [comment]
I'm assuming you're trying to make a Fabric mod (as that is the only use for yarn mappings), so for that you can look at geniiii's far lands mod for reference: https://github.com/geniiii/FarLands/blob/master/src/main/java/site/geni/farlands/mixins/common/noise/OctavePerlinNoiseSamplerMixin.java
