### ISSUE TITLE
Some further Far Lands related phenomena

### ISSUE THREAD

**Issue by muzikbike** [ThisTestUser/FarLandsChronicles#7]
Here's a few more very interesting details relating to the Far Lands that could warrant investigation or a mention.

### Sheet Far Lands

Interestingly, this one can be generated completely in vanilla (14w17a-18w05a) using Customized world settings. If we set the coordinate scale to 532676640, we get a world that looks pretty rough as one would expect. However, teleporting to exactly 2,097,152 blocks out brings us this freak of nature:

![2021-01-26_02 28 10](https://user-images.githubusercontent.com/52297970/105794903-d8f19e80-5f83-11eb-993b-58488b5a83d6.png)

These thin walls can absolutely intersect themselves as one would expect (they generate on both axes), which can result in 3x3 versions of The Stack.

![2021-01-26_02 28 57](https://user-images.githubusercontent.com/52297970/105794921-e0b14300-5f83-11eb-8bc3-ef749d41b42f.png)
![2021-01-26_02 29 32](https://user-images.githubusercontent.com/52297970/105794925-e1e27000-5f83-11eb-9da7-090b8f2f51e6.png)
![2021-01-26_02 30 19](https://user-images.githubusercontent.com/52297970/105794928-e3139d00-5f83-11eb-8dd4-4802c4c51c02.png)

And yes, they can mix with the Sky Far Lands in about the way you would expect:

![2021-01-26_02 36 21](https://user-images.githubusercontent.com/52297970/105794941-e7d85100-5f83-11eb-9929-9ac972a022b1.png)

If we increase this be 32 (the minimum number it can be increased by as coordinateScale is a float) to 532676672 the first sheet now appears at 1,048,576 (2,097,152/2) blocks, and adding 32 again to make it 532676704 causes it to be at 699050 blocks (2,097,152/3).

If instead of doing this for coordinateScale, we instead set this number for one or both of the depth noise scales and teleport the expected distance, a ridge can be found in that exact same location:

![2021-01-26_02 40 40](https://user-images.githubusercontent.com/52297970/105794954-ef97f580-5f83-11eb-9c3a-db7ea7e27ad3.png)
![2021-01-26_02 40 46](https://user-images.githubusercontent.com/52297970/105794956-f0c92280-5f83-11eb-8d2f-61ec395abb70.png)

### Low/high noise disjoint generation

The usual Far Lands are caused by the simultaneous overflowing of what are know as low noise and high noise. While usually inseperable in vanilla (although proving this otherwise would be great), CubicWorldGen allows them to be configured separately, and this of course allows them to overflow at different distances, causing exciting effects. In the following examples, low noise is set to overflow at twice the usual Far Lands distance on the X axis, and high noise twice as far on the Z axis, in order to see how weirdly these can mix.

Positive X (high noise only)

![2021-01-26_02 57 36](https://user-images.githubusercontent.com/52297970/105794987-fde61180-5f83-11eb-97fa-770ad0827a4a.png)
![2021-01-26_02 57 41](https://user-images.githubusercontent.com/52297970/105794988-ff173e80-5f83-11eb-9db1-c0f0e3e0e879.png)
![2021-01-26_02 59 43](https://user-images.githubusercontent.com/52297970/105794990-ffafd500-5f83-11eb-8f28-fbe0b6166e6e.png)

Positive Z (low noise only)

![2021-01-26_03 01 14](https://user-images.githubusercontent.com/52297970/105795007-09393d00-5f84-11eb-8e2b-cc70c698ba84.png)
![2021-01-26_03 01 22](https://user-images.githubusercontent.com/52297970/105795008-09d1d380-5f84-11eb-9cc4-19405d855292.png)

And when we go to 25,101,640 blocks out where both should be overflowing, terrain just becomes outright unexplainable. There are tunnels underneath other tunnels that run completely perpendicular to each other, and so on. The proper boundary can be seen in some cases, but only some.

![2021-01-26_03 04 28](https://user-images.githubusercontent.com/52297970/105795021-13f3d200-5f84-11eb-8cee-451b73fbf73e.png)
![2021-01-26_03 04 48](https://user-images.githubusercontent.com/52297970/105795024-1524ff00-5f84-11eb-972b-85e7fa4614c6.png)
![2021-01-26_03 05 01](https://user-images.githubusercontent.com/52297970/105795030-15bd9580-5f84-11eb-9e74-36d28a4cde3d.png)
![2021-01-26_03 05 48](https://user-images.githubusercontent.com/52297970/105795033-16eec280-5f84-11eb-8cc4-b3f8c1163579.png)
![2021-01-26_03 07 20](https://user-images.githubusercontent.com/52297970/105795036-17875900-5f84-11eb-92e9-0733913c9c4b.png)

**Comment by muzikbike** [comment]
Here's a view of the first Corner "Far Lands". Not too much special looking about it:
![2021-01-26_03 18 27](https://user-images.githubusercontent.com/52297970/105795982-b6f91b80-5f85-11eb-846e-826076a84238.png)

If we go onto the tubes on the right, we reach a clearing. And looking to the left reveals what looks to be literal Edge Far Lands (and probably is Edge Far Lands - since one noise generator hasn't overflowed in the clearing and finally overflows past that point) staring right back at us despite already being in the other set of Edge Far Lands:
![2021-01-26_03 18 18](https://user-images.githubusercontent.com/52297970/105796083-f58ed600-5f85-11eb-9d47-7a0353c22fd6.png)

Yet if we were to fly into one of these tunnels, what we would be greeted with is another set of Edge Far Lands, which again are pointing perpendicularly to this set:
![2021-01-26_03 19 05](https://user-images.githubusercontent.com/52297970/105796130-11927780-5f86-11eb-9db8-b40f9b0a95ce.png)

And a view of those from a clearing:
![2021-01-26_03 20 52](https://user-images.githubusercontent.com/52297970/105796150-1d7e3980-5f86-11eb-9085-581a53d7d6fc.png)

Actual Corner Far Lands looking terrain is pretty rare in this region.
![2021-01-26_03 26 13](https://user-images.githubusercontent.com/52297970/105796234-51f1f580-5f86-11eb-9517-ed580d9fc525.png)

And the corner far lands, at least when far enough that both noises have long since overflowed, look pretty standard:
![2021-01-26_03 43 28](https://user-images.githubusercontent.com/52297970/105798482-22dd8300-5f8a-11eb-9f5a-cb7af09d7724.png)
![2021-01-26_03 44 44](https://user-images.githubusercontent.com/52297970/105798484-23761980-5f8a-11eb-920a-a05df6e95717.png)

A couple other things I decided to do after this, alongside lowering height offset and the sea level to 0 and -1 and making the vertical edge far lands spawn at the other edge far lands distances, was to mess around with this some more. Since selector noise is what is used to determine whether high noise or low noise is used at a given point, having it overflow before low or high noise did would yield interesting results. So I set it to overflow at half the far lands distance, and it of course yielded some rather interesting effects.

![2021-01-28_06 01 52](https://user-images.githubusercontent.com/52297970/106097493-5279c000-612f-11eb-9e32-fa683e5d8d23.png)
![2021-01-28_06 02 52](https://user-images.githubusercontent.com/52297970/106097496-53125680-612f-11eb-99eb-85936e787696.png)
![2021-01-28_06 04 04](https://user-images.githubusercontent.com/52297970/106097498-54438380-612f-11eb-80d2-8e0ccbe93c3a.png)
![2021-01-28_06 06 15](https://user-images.githubusercontent.com/52297970/106097504-54dc1a00-612f-11eb-9429-1efcfb10398a.png)

**Comment by muzikbike** [comment]
Another misc thing I've heard is that the Fartherer Lands actually completely stop after twice the distance they initiate at. I've tried testing this in vanilla 18w05a with the coordinate scale 2939527156989.952, and while i could definitely see Fartherer Lands (read: a noticeable change in the already stupidly chaotic terrain) there didn't seem to be any changes of note at twice the distance. Maybe offsetting could provide something different?

**Comment by ThisTestUser** [comment]
I looked at the sheet far lands and it seems like it is entirely dependent on the coordinate scale and not distance. The normal vanilla far lands do generate, but it clashes with the sheet far lands:
![clash](https://raw.githubusercontent.com/ThisTestUser/FarLandsChronicles/master/assets/Ch5/CoordScaleFar1.png)
For the fartherer lands, the jump in the terrain only appears in Forge and not vanilla (as I have documented in this repo), but the terrain does jump back eventually:
![jumpback](https://raw.githubusercontent.com/ThisTestUser/FarLandsChronicles/master/assets/Ch5/FarLandsDropBackForge.png)
